name: editnova
description: AI-powered all-in-one editor
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  file_picker: ^10.2.0
  flutter_colorpicker: ^1.0.3
  image: ^4.5.4
  flutter_speed_dial: ^7.0.0
  animated_text_kit: ^4.2.2
  lottie: ^3.3.1
  speech_to_text: ^7.2.0
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700